services:
  - type: web
    name: cafeteria-backend
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: ./backend_Cafeteria
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: ./data/cafeteria.db  

  - type: static
    name: cafeteria-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: ./cafeteria-app
    envVars:
      - key: VITE_API_URL
        value: https://cafeteria-backend.onrender.com